spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/lession_13
    username: postgres
    password: Muhammad2323.
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update          # create / validate / none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false

  flyway:
    enabled: false              # пока можно выключить

logging:
  level:
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
